spring:
  profiles:
    active:
      - dev
#      - prod

---
#logging:
#  level:
#    .: debug
#    org.springframework: WARN

spring:
  profiles: dev
  name: dev-your-paper

  batch:
    job:
      enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${LOCAL_DB_URL}/your_paper_dev
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}


  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop

---
logging:
  level:
    .: error
    org.springframework: ERROR

spring:
  profiles: prod
  name: prod-your-paper


  batch:
    job:
      enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${LOCAL_DB_URL}/your_paper
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}


  jpa:
    show-sql: true
    database: mysql
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

