spring:
  application:
    name: UPMUREPORT-WEB
  
  data:
    rest:
      base-path: /api
      
  profiles:
    active:
      - dev
      # - prod
  
  main:
    allow-bean-definition-overriding: true
  
server:
  port: ${SERVER_PORT}

---  
spring.profiles: dev
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME_DEV}
    password: ${DATASOURCE_PASSWORD_DEV}
    
  jpa:
    properties:
      hibernate:
        hbm2dd:
          auto: update
        dialect: org.hibernate.dialect.MariaDBDialect
        enable_lazy_load_no_trans: true
        
---
spring.profiles: prod
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    
  jpa:
    properties:
      hibernate:
        hbm2dd:
          auto: update
        dialect: org.hibernate.dialect.MariaDBDialect
        enable_lazy_load_no_trans: true